In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

# If notebook is at testing/wfp_food_prices.ipynb:
# parents[1] => project root
ROOT = Path.cwd().parents[0] if Path.cwd().name == "testing" else Path.cwd()
DATASET_DIR = ROOT / "dataset"

input_csv = DATASET_DIR / "wfp_food_prices_global_2026.csv"

df = pd.read_csv(input_csv)

In [3]:
df.head()

,countryiso3,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,AFG,2026-05-15,Badakhshan,Argo,Badakhshan,3690,37.04,70.46,cereals and tubers,Bread,55,KG,actual,Retail,AFN,77.0,1.20
1,AFG,2026-05-15,Badakhshan,Argo,Badakhshan,3690,37.04,70.46,cereals and tubers,Rice (high quality),247,KG,actual,Retail,AFN,131.0,2.05
2,AFG,2026-05-15,Badakhshan,Argo,Badakhshan,3690,37.04,70.46,cereals and tubers,Rice (low quality),145,KG,actual,Retail,AFN,66.0,1.03
3,AFG,2026-05-15,Badakhshan,Argo,Badakhshan,3690,37.04,70.46,cereals and tubers,Wheat,84,KG,actual,Retail,AFN,27.0,0.42
4,AFG,2026-05-15,Badakhshan,Argo,Badakhshan,3690,37.04,70.46,cereals and tubers,Wheat flour (high quality),178,KG,actual,Retail,AFN,33.0,0.52

In [4]:
for col in df.columns:
    print(f"{col}: {list(df[col].unique())}")

countryiso3: ['AFG', 'ARM', 'BDI', 'BEN', 'BFA', 'BGD', 'BOL', 'CAF', 'CIV', 'CMR', 'COD', 'COG', 'DZA', 'ECU', 'EGY', 'ETH', 'GIN', 'GMB', 'GTM', 'IDN', 'IND', 'IRN', 'IRQ', 'JOR', 'KEN', 'KGZ', 'KHM', 'LAO', 'LBN', 'LBY', 'LSO', 'MDA', 'MDG', 'MLI', 'MMR', 'MRT', 'MWI', 'NER', 'NGA', 'NIC', 'NPL', 'PAK', 'PHL', 'PSE', 'RWA', 'SDN', 'SEN', 'SLV', 'SOM', 'SSD', 'SYR', 'TCD', 'TJK', 'TLS', 'TUR', 'TZA', 'UGA', 'UKR', 'YEM', 'ZMB']
date: ['2026-05-15', '2026-04-15', '2026-01-15', '2026-02-15', '2026-03-15', '2026-12-15']
admin1: ['Badakhshan', 'Badghis', 'Baghlan', 'Balkh', 'Bamyan', 'Daykundi', 'Farah', 'Faryab', 'Ghazni', 'Ghor', 'Hilmand', 'Hirat', 'Jawzjan', 'Kabul', 'Kandahar', 'Kapisa', 'Khost', 'Kunar', 'Kunduz', 'Laghman', 'Logar', 'Nangarhar', 'Nimroz', 'Nuristan', 'Paktika', 'Paktya', 'Panjsher', 'Parwan', 'Samangan', 'Sar-e-pul', 'Takhar', 'Uruzgan', 'Wardak', 'Zabul', 'Aragatsotn', 'Ararat', 'Armavir', 'Gegharkunik', 'Kotayk', 'Lori', 'Shirak', 'Syunik', 'Tavush', 'Vayotz Dzor', 'Yerevan', 'Bubanza', 'Bujumbura Mairie', 'Bujumbura Rural', 'Bururi', 'Cankuzo', 'Cibitoke', 'Gitega', 'Karuzi', 'Kayanza', 'Kirundo', 'Makamba', 'Muramvya', 'Muyinga', 'Mwaro', 'Ngozi', 'Rumonge', 'Rutana', 'Ruyigi', 'Alibori', 'Atakora', 'Atlantique', 'Borgou', 'Collines', 'Couffo', 'Donga', 'Littoral', 'Mono', 'Oueme', 'Plateau', 'Zou', 'BOUCLE DU MOUHOUN', 'CASCADES', 'CENTRE', 'CENTRE-EST', 'CENTRE-NORD', 'CENTRE-OUEST', 'CENTRE-SUD', 'EST', 'HAUTS-BASSINS', 'NORD', 'PLATEAU-CENTRAL', 'SAHEL', 'SUD-OUEST', 'Barisal', 'Chittagong', 'Dhaka', 'Khulna', 'Mymensingh', 'Rajshahi', 'Rangpur', 'Sylhet', 'Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija', 'Bamingui-Bangoran', 'Bangui', 'Haut-Mbomou', 'Haute-Kotto', 'Kémo', 'Mambéré-Kadéï', 'Mbomou', 'Nana-Gribizi', 'Nana-Mambéré', "Ombella M'Poko", 'Ouaka', 'Ouham', 'Ouham Pendé', 'Sangha-Mbaéré', 'Vakaga', 'Montagnes', 'Savanes', 'Adamaoua', 'Extrême-Nord', 'Nord', 'Centre', 'Nord-Ouest', 'Sud-Ouest', 'Equateur', 'Haut-Katanga', 'Ituri', 'Kasai', 'Kasai-Central', 'Kasai-Oriental', 'Kongo-Central', 'Kwango', 'Lualaba', 'Mai-Ndombe', 'Maniema', 'Nord-Kivu', 'Sankuru', 'Sud-Kivu', 'Tanganyika', 'Tshopo', 'Tshuapa', 'Bas-Uele', 'Haut-Lomami', 'Haut-Uele', 'Kwilu', 'Lomami', 'Nord-Ubangi', 'Sud-Ubangi', 'Brazzaville', 'Likouala', 'Point-Noire', 'Tindouf', 'Guayas', 'Pichincha', 'Cairo', 'Afar', 'Amhara', 'B. Gumuz', 'Dire Dawa', 'Gambela', 'Harari', 'Oromia', 'SNNPR', 'Somali', 'Tigray', 'Boke', 'Faranah', 'Kankan', 'Kindia', 'Labe', 'Nzerekore', 'Central River', 'Kanifing Municipal Council', 'Lower River', 'North Bank', 'Upper River', 'West Coast', 'Guatemala', 'BALI', 'JAWA TENGAH', 'JAWA TIMUR', 'KALIMANTAN TIMUR', 'PAPUA', 'PAPUA BARAT', 'SUMATERA BARAT', 'SUMATERA UTARA', 'Assam', 'Karnataka', 'Maharashtra', 'Orissa', 'Rajasthan', 'Tehran', 'Anbar', 'Babil', 'Baghdad', 'Basrah', 'Dahuk', 'Diyala', 'Erbil', 'Kerbala', 'Kirkuk', 'Missan', 'Muthanna', 'Najaf', 'Ninewa', 'Qadissiya', 'Salah al-Din', 'Sulaymaniyah', 'Thi-Qar', 'Wassit', 'Ajloun', 'Al  Aqaba', 'Al Balqa', 'Al Karak', 'Al Mafraq', 'Al Tafilah', 'Amman', 'Irbid', 'Jarash', 'Maan', 'Madaba', 'Zarqa', 'Nairobi', 'Nyanza', 'North Eastern', 'Batken', 'Bishkek (city)', 'Chui', 'Issyk-Kul', 'Jalal-Abad', 'Naryn', 'Osh', 'Osh (city)', 'Talas', 'Banteay Meanchey', 'Battambang', 'Kampong Cham', 'Kampong Chhnang', 'Kampong Thom', 'Koh Kong', 'Oddar Meanchey', 'Pailin', 'Preah Vihear', 'Pursat', 'Siemreap', 'Stung Treng', 'Attapeu', 'Bokeo', 'Bolikhamxai', 'Champasack', 'Houaphan', 'Khammouan', 'Louangnamtha', 'Louangphabang', 'Oudomxai', 'Phongsaly', 'Salavan', 'Savannakhet', 'Sekong', 'Vientiane', 'Vientiane Capital', 'Xaignabouly', 'Xiengkhouang', 'Akkar', 'Baalbek-El Hermel', 'Beirut', 'Bekaa', 'El Nabatieh', 'Mount Lebanon', 'North', 'South', 'East', 'West', 'Berea', 'Butha-Buthe', 'Leribe', 'Mafeteng', 'Maseru', "Mohale's Hoek", 'Mokhotlong', "Qacha's Nek", 'Quthing', 'Thaba-Tseka', 'Chisinau', 'Dubasari', 'Androy', 'Anosy', 'Atsimo Andrefana', 'Atsimo Atsinanana', 'Vatovavy Fitovinany', 'Bamako', 'Gao', 'Kayes', 'Kidal', 'Koulikoro', 'Mopti', 'Segou', 'Sikasso', 'Tombouctou', 'Bago (East)', 'Chin', 'Kachin', 'Kayah', 'Kayin', 'Magway', 'Mandalay', 'Mon', 'Rakhine', 'Sagaing', 'Shan (North)', 'Shan (South)', 'Tanintharyi', 'Yangon', 'Adrar', 'Assaba', 'Brakna', 'Dakhlet-Nouadhibou', 'Guidimakha', 'Hodh El Gharbi', 'Trarza', 'Hodh Ech Chargi', 'Central Region', 'Northern Region', 'Southern Region', 'Agadez', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Tillaberi', 'Zinder', 'Borno', 'Yobe', nan, 'Province No. 1', 'Province No. 2', 'Province No. 3', 'Province No. 4', 'Province No. 5', 'Province No. 6', 'Province No. 7', 'BALOCHISTAN', 'KHYBER PAKHTUNKHWA', 'PUNJAB', 'SINDH', 'Autonomous region in Muslim Mindanao', 'Cordillera Administrative region', 'National Capital region', 'Region I', 'Region II', 'Region III', 'Region IV-A', 'Region IV-B', 'Region IX', 'Region V', 'Region VI', 'Region VII', 'Region VIII', 'Region X', 'Region XI', 'Region XII', 'Region XIII', 'Gaza Strip', 'West Bank', 'Eastern Province', 'Southern Province', 'Western Province', 'Al Gezira', 'Blue Nile', 'Central Darfur', 'Eastern Darfur', 'Gedaref', 'Kassala', 'Khartoum', 'Nile', 'North Darfur', 'North Kordofan', 'Northern', 'Red Sea', 'Sennar', 'South Darfur', 'South Kordofan', 'West Darfur', 'West Kordofan', 'White Nile', 'Dakar', 'Diourbel', 'Fatick', 'Kaolack', 'Kedougou', 'Kolda', 'Louga', 'Matam', 'Saint Louis', 'Sedhiou', 'Tambacounda', 'Thies', 'Ziguinchor', 'SAN SALVADOR', 'Awdal', 'Bakool', 'Banadir', 'Bari', 'Bay', 'Galgaduud', 'Gedo', 'Hiraan', 'Juba Hoose', 'Mudug', 'Nugaal', 'Sanaag', 'Shabelle Dhexe', 'Sool', 'Togdheer', 'Woqooyi Galbeed', 'Central Equatoria', 'Eastern Equatoria', 'Jonglei', 'Lakes', 'Northern Bahr el Ghazal', 'Unity', 'Upper Nile', 'Warrap', 'Western Equatoria', 'Al-Hasakeh', 'Aleppo', 'Ar-Raqqa', 'As-Sweida', 'Damascus', "Dar'a", 'Deir-ez-Zor', 'Hama', 'Homs', 'Idleb', 'Lattakia', 'Quneitra', 'Rural Damascus', 'Tartous', 'Barh El Gazal', 'Batha', 'Borkou', 'Chari Baguirmi', 'Ennedi Est', 'Ennedi Ouest', 'Guera', 'Hadjer Lamis', 'Kanem', 'Lac', 'Logone Occidental', 'Logone Oriental', 'Mandoul', 'Mayo Kebbi Est', 'Mayo Kebbi Ouest', 'Moyen Chari', 'Ndjaména', 'Ouaddai', 'Salamat', 'Sila', 'Tandjile', 'Wadi Fira', 'Districts of Republican Subordination', 'Gorno-Badakhshan Autonomous Province', 'Khatlon', 'Sughd', 'Bobonaro', 'Covalima', 'Dili', 'Ermera', 'Manatuto', 'Oecussi', 'Baucau', 'Ankara', 'Arusha', 'Dar-es-salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera', 'Katavi', 'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara', 'Mbeya', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu', 'Singida', 'Tabora', 'Tanga', 'Abim', 'Adjumani', 'Amudat', 'Arua', 'Gulu', 'Hoima', 'Isingiro', 'Jinja', 'Kaabong', 'Kabarole', 'Kampala', 'Kamwenge', 'Kiryandongo', 'Koboko', 'Kotido', 'Kyegegwa', 'Lamwo', 'Masaka', 'Mbale', 'Mbarara', 'Moroto', 'Moyo', 'Nakapiripirit', 'Napak', 'Yumbe', 'Cherkaska', 'Chernihivska', 'Chernivetska', 'Dnipropetrovska', 'Ivano-Frankivska', 'Kharkivska', 'Khersonska', 'Khmelnytska', 'Kirovohradska', 'Kyivska', 'Lvivska', 'Mykolaivska', 'Odeska', 'Poltavska', 'Rivnenska', 'Sumska', 'Ternopilska', 'Vinnytska', 'Volynska', 'Zakarpatska', 'Zaporizka', 'Zhytomyrska', 'Abyan', 'Aden', "Al Dhale'e", 'Al Maharah', 'Hadramaut', 'Lahj', 'Marib', 'Shabwah', 'Socotra', 'Taizz', 'Central', 'Copperbelt', 'Luapula', 'Lusaka', 'Muchiga']

In [5]:
df_sample = df[df["unit"].isin(["KG", "Pound", "1 piece"])].copy()
df_sample.loc[df_sample["unit"] == "Pound", "unit"] = "Lbs"
df_sample.loc[df_sample["unit"] == "1 piece", "unit"] = "Pcs"
df_sample = df_sample[df_sample["currency"].isin(["USD", "IDR", "KHR", "LAK", "MMK", "PHP"])]
df_sample = df_sample[df_sample["pricetype"] == "Retail"]
df_sample = df_sample[df_sample["priceflag"] == "actual"]
df_sample.head()

,countryiso3,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
22695,ECU,2026-01-15,Guayas,Guayaquil,Guayaquil,2582,-2.2,-79.9,cereals and tubers,Bread,55,KG,actual,Retail,USD,2.12,2.12
22696,ECU,2026-01-15,Guayas,Guayaquil,Guayaquil,2582,-2.2,-79.9,cereals and tubers,Cassava,68,KG,actual,Retail,USD,0.93,0.93
22697,ECU,2026-01-15,Guayas,Guayaquil,Guayaquil,2582,-2.2,-79.9,cereals and tubers,Maize,51,KG,actual,Retail,USD,2.02,2.02
22698,ECU,2026-01-15,Guayas,Guayaquil,Guayaquil,2582,-2.2,-79.9,cereals and tubers,Noodles (short),126,KG,actual,Retail,USD,2.41,2.41
22699,ECU,2026-01-15,Guayas,Guayaquil,Guayaquil,2582,-2.2,-79.9,cereals and tubers,Potatoes,83,KG,actual,Retail,USD,0.87,0.87